services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/image_db
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=100
    depends_on:
      - mongo
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./public:/app/public  # Add public folder
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: